<?php

namespace Repositories;

class HouseRepository extends PropertyRepository {

    public function __construct()
    {
        parent::__construct();
    }

    public function create(): void
    {
    parent::create(); // TODO: Change the autogenerated stub
    }
}